version: '3.8'

services:
  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb_data:/opt/couchdb/data

  backend:
    image: practobz/backend:1.0CO
    ports:
      - "3000:3000"
    depends_on:
      - couchdb
    environment:
      - COUCHDB_URL=http://admin:admin@couchdb:5984

volumes:
  couchdb_data:
